export const AppLocale = { En: 'en', Zh: 'zh' };

const strings = {
  en: {
    appName: 'Desk Tidy Sticky',
    inputHint: 'Type a note... (Enter to save)',
    saveNote: 'Save',
    saveNoteAction: 'Save note',
    cancel: 'Cancel',
    hideAfterSave: 'Hide after save',
    active: 'Active',
    todo: 'Todo',
    quadrant: 'Quadrant',
    archived: 'Archived',
    overlay: 'Desktop overlay',
    searchHint: 'Search (pinyin supported)...',
    edit: 'Edit',
    delete: 'Delete',
    clear: 'Clear',
    hideWindow: 'Hide window',
    language: 'Language',
    archive: 'Archive',
    unarchive: 'Unarchive',
    pinWindow: 'Pin window',
    unpinWindow: 'Unpin window',
    pinNote: 'Pin note',
    unpinNote: 'Unpin note',
    markDone: 'Mark done',
    markUndone: 'Mark undone',
    overlayClickThrough: 'Mouse interaction',
    overlayClose: 'Close overlay',
    overlayTip: 'Use Ctrl+Shift+O or tray to toggle mouse interaction',
    trayShowMain: 'Show main window',
    trayShowNotes: 'Show main window',
    trayGithub: 'Star on GitHub',
    trayStickiesClose: 'Overlay: Close',
    trayStickiesShow: 'Desktop overlay',
    trayInteraction: 'Overlay: Toggle mouse interaction',
    trayQuit: 'Exit',
    glassAdjust: 'Scroll to adjust opacity',
    sortByCustom: 'Manual',
    sortByNewest: 'Newest',
    sortByOldest: 'Oldest',
    sortMode: 'Sort',
    trash: 'Trash',
    restore: 'Restore',
    permanentlyDelete: 'Permanent delete',
    emptyTrash: 'Empty trash',
    pinToTop: 'Always on Top',
    pinToBottom: 'Pin to Bottom',
    frost: 'Frost',
    textColor: 'Text color',
    customColor: 'Custom',
    dragToReorder: 'Drag to reorder',
    priority: 'Priority',
    quadrantQ1: 'Q1 Important + Urgent',
    quadrantQ2: 'Q2 Important + Not Urgent',
    quadrantQ3: 'Q3 Urgent + Not Important',
    quadrantQ4: 'Q4 Routine / Later',
    quadrantQ1Desc: 'Do first',
    quadrantQ2Desc: 'Schedule',
    quadrantQ3Desc: 'Delegate / fast handle',
    quadrantQ4Desc: 'Backlog',
    emptyInQuadrant: 'No notes in this quadrant',
    settings: 'Settings',
    workspaceTitle: 'Workspace',
    details: 'Details',
    inspectorExpand: 'Expand',
    inspectorRestore: 'Restore split',
    maximizeWindow: 'Maximize window',
    restoreWindow: 'Restore window',
    workspaceHint: 'Complex planning workspace',
    switchToWorkspace: 'Open workspace',
    switchToCompact: 'Compact mode',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
    themeLight: 'Light mode',
    themeDark: 'Dark mode',
    settingsTitle: 'Settings',
    starOnGithub: 'Star on GitHub',
    general: 'General',
    autoStart: 'Start on Boot',
    showPanelOnStartup: 'Show panel on startup',
    shortcuts: 'Shortcuts',
    shortcutToggle: 'Toggle Panel: Ctrl+Shift+N',
    shortcutOverlay: 'Toggle Overlay Input: Ctrl+Shift+O',
    shortcutEsc: 'Hide/Exit Interaction: Escape',
    shortcutPinSave: 'Pin & Save: Ctrl+Enter',
    version: 'Version v1.0.0',
    close: 'Close',
    editorBlockMode: 'Block editor',
    editorSourceMode: 'Source only'
  },
  zh: {
    appName: 'Desk Tidy 便笺',
    inputHint: '输入便笺…（回车保存）',
    saveNote: '保存',
    saveNoteAction: '保存便笺',
    cancel: '取消',
    hideAfterSave: '保存后隐藏',
    active: '活动',
    todo: '待办',
    quadrant: '四象限',
    archived: '已归档',
    overlay: '桌面贴纸',
    searchHint: '搜索（支持拼音）…',
    edit: '编辑',
    delete: '删除',
    clear: '清除',
    hideWindow: '隐藏窗口',
    language: '语言',
    archive: '归档',
    unarchive: '恢复',
    pinWindow: '窗口置顶',
    unpinWindow: '取消置顶',
    pinNote: '钉住便笺',
    unpinNote: '取消钉住',
    markDone: '标记完成',
    markUndone: '取消完成',
    overlayClickThrough: '鼠标交互',
    overlayClose: '关闭贴纸',
    overlayTip: '用 Ctrl+Shift+O 或托盘切换鼠标交互',
    trayShowMain: '显示主窗口',
    trayShowNotes: '显示主窗口',
    trayGithub: '在 GitHub 上点星',
    trayStickiesClose: '贴纸：关闭',
    trayStickiesShow: '桌面贴纸',
    trayInteraction: '贴纸：切换鼠标交互',
    trayQuit: '退出',
    glassAdjust: '滚轮调节透明度',
    sortByCustom: '手动',
    sortByNewest: '最新',
    sortByOldest: '最早',
    sortMode: '排序',
    trash: '回收站',
    restore: '恢复',
    permanentlyDelete: '永久删除',
    emptyTrash: '清空回收站',
    pinToTop: '置顶显示',
    pinToBottom: '贴在底部',
    frost: '磨砂',
    textColor: '文字颜色',
    customColor: '自定义',
    dragToReorder: '拖动排序',
    priority: '优先级',
    quadrantQ1: 'Q1 重要且紧急',
    quadrantQ2: 'Q2 重要不紧急',
    quadrantQ3: 'Q3 紧急不重要',
    quadrantQ4: 'Q4 常规/稍后',
    quadrantQ1Desc: '优先处理',
    quadrantQ2Desc: '计划推进',
    quadrantQ3Desc: '快速处理/委派',
    quadrantQ4Desc: '积压池',
    emptyInQuadrant: '该象限暂无事项',
    settings: '设置',
    workspaceTitle: '工作台',
    details: '详情',
    inspectorExpand: '放大',
    inspectorRestore: '还原分栏',
    maximizeWindow: '窗口最大化',
    restoreWindow: '窗口还原',
    workspaceHint: '复杂任务与规划视图',
    switchToWorkspace: '打开工作台',
    switchToCompact: '简洁模式',
    collapseSidebar: '收起侧栏',
    expandSidebar: '展开侧栏',
    themeLight: '浅色模式',
    themeDark: '深色模式',
    settingsTitle: '设置',
    starOnGithub: '在 GitHub 上点星',
    general: '常规',
    autoStart: '开机自启',
    showPanelOnStartup: '启动时显示主窗口',
    shortcuts: '快捷键',
    shortcutToggle: '切换主窗口: Ctrl+Shift+N',
    shortcutOverlay: '切换贴纸鼠标交互: Ctrl+Shift+O',
    shortcutEsc: '隐藏/退出交互: Escape (Esc)',
    shortcutPinSave: '保存并置顶: Ctrl+Enter',
    version: '版本 v1.0.0',
    close: '关闭',
    editorBlockMode: '块编辑',
    editorSourceMode: '仅源码'
  }
};

/** @param {string} locale */
export function getStrings(locale) {
  return strings[locale === 'zh' ? 'zh' : 'en'] || strings.en;
}
