export const AppLocale = { En: 'en', Zh: 'zh' };

const strings = {
  en: {
    appName: 'Desk Tidy Sticky',
    inputHint: 'Type a note... (Enter to save)',
    saveNote: 'Save',
    saveNoteAction: 'Save note',
    cancel: 'Cancel',
    hideAfterSave: 'Hide after save',
    active: 'Active',
    archived: 'Archived',
    overlay: 'Desktop overlay',
    searchHint: 'Search (pinyin supported)...',
    edit: 'Edit',
    delete: 'Delete',
    clear: 'Clear',
    hideWindow: 'Hide window',
    language: 'Language',
    archive: 'Archive',
    unarchive: 'Unarchive',
    pinWindow: 'Pin window',
    unpinWindow: 'Unpin window',
    pinNote: 'Pin note',
    unpinNote: 'Unpin note',
    markDone: 'Mark done',
    markUndone: 'Mark undone',
    overlayClickThrough: 'Mouse interaction',
    overlayClose: 'Close overlay',
    overlayTip: 'Use Ctrl+Shift+O or tray to toggle mouse interaction',
    trayShowNotes: 'Show notes',
    trayGithub: 'Star on GitHub',
    trayStickiesClose: 'Overlay: Close',
    trayStickiesShow: 'Desktop overlay',
    trayInteraction: 'Overlay: Toggle mouse interaction',
    trayQuit: 'Exit',
    glassAdjust: 'Scroll to adjust opacity',
    sortByCustom: 'Manual',
    sortByNewest: 'Newest',
    sortByOldest: 'Oldest',
    sortMode: 'Sort',
    trash: 'Trash',
    restore: 'Restore',
    permanentlyDelete: 'Permanent delete',
    emptyTrash: 'Empty trash',
    pinToTop: 'Always on Top',
    pinToBottom: 'Pin to Bottom',
    frost: 'Frost',
    textColor: 'Text color',
    dragToReorder: 'Drag to reorder',
    settings: 'Settings',
    settingsTitle: 'Settings',
    starOnGithub: 'Star on GitHub',
    general: 'General',
    autoStart: 'Start on Boot',
    showPanelOnStartup: 'Show panel on startup',
    shortcuts: 'Shortcuts',
    shortcutToggle: 'Toggle Panel: Ctrl+Shift+N',
    shortcutOverlay: 'Toggle Overlay Input: Ctrl+Shift+O',
    shortcutEsc: 'Hide/Exit Interaction: Escape',
    shortcutPinSave: 'Pin & Save: Ctrl+Enter',
    version: 'Version v1.0.0',
    close: 'Close',
    editorBlockMode: 'Block editor',
    editorSplitMode: 'Split edit + preview',
    editorSourceMode: 'Source only'
  },
  zh: {
    appName: 'Desk Tidy 便笺',
    inputHint: '输入便笺…（回车保存）',
    saveNote: '保存',
    saveNoteAction: '保存便笺',
    cancel: '取消',
    hideAfterSave: '保存后隐藏',
    active: '活动',
    archived: '已归档',
    overlay: '桌面贴纸',
    searchHint: '搜索（支持拼音）…',
    edit: '编辑',
    delete: '删除',
    clear: '清除',
    hideWindow: '隐藏窗口',
    language: '语言',
    archive: '归档',
    unarchive: '恢复',
    pinWindow: '窗口置顶',
    unpinWindow: '取消置顶',
    pinNote: '钉住便笺',
    unpinNote: '取消钉住',
    markDone: '标记完成',
    markUndone: '取消完成',
    overlayClickThrough: '鼠标交互',
    overlayClose: '关闭贴纸',
    overlayTip: '用 Ctrl+Shift+O 或托盘切换鼠标交互',
    trayShowNotes: '显示便笺',
    trayGithub: '在 GitHub 上点星',
    trayStickiesClose: '贴纸：关闭',
    trayStickiesShow: '桌面贴纸',
    trayInteraction: '贴纸：切换鼠标交互',
    trayQuit: '退出',
    glassAdjust: '滚轮调节透明度',
    sortByCustom: '手动',
    sortByNewest: '最新',
    sortByOldest: '最早',
    sortMode: '排序',
    trash: '回收站',
    restore: '恢复',
    permanentlyDelete: '永久删除',
    emptyTrash: '清空回收站',
    pinToTop: '置顶显示',
    pinToBottom: '贴在底部',
    frost: '磨砂',
    textColor: '文字颜色',
    dragToReorder: '拖动排序',
    settings: '设置',
    settingsTitle: '设置',
    starOnGithub: '在 GitHub 上点星',
    general: '常规',
    autoStart: '开机自启',
    showPanelOnStartup: '启动时显示主窗口',
    shortcuts: '快捷键',
    shortcutToggle: '切换主窗口: Ctrl+Shift+N',
    shortcutOverlay: '切换贴纸鼠标交互: Ctrl+Shift+O',
    shortcutEsc: '隐藏/退出交互: Escape (Esc)',
    shortcutPinSave: '保存并置顶: Ctrl+Enter',
    version: '版本 v1.0.0',
    close: '关闭',
    editorBlockMode: '块编辑',
    editorSplitMode: '分栏编辑预览',
    editorSourceMode: '仅源码'
  }
};

/** @param {string} locale */
export function getStrings(locale) {
  return strings[locale === 'zh' ? 'zh' : 'en'] || strings.en;
}
