export const AppLocale = { En: 'en', Zh: 'zh' };

const strings = {
  en: {
    appName: 'Desk Tidy Sticky',
    inputHint: 'Type a note... (Enter to save)',
    saveNote: 'Save',
    saveNoteAction: 'Save note',
    cancel: 'Cancel',
    hideAfterSave: 'Hide main panel after save',
    compactActive: 'Active',
    active: 'All',
    todo: 'Todo',
    quadrant: 'Quadrant',
    archived: 'Archived',
    overlay: 'Enable desktop overlay',
    searchHint: 'Search (pinyin supported)...',
    edit: 'Edit',
    delete: 'Delete',
    clear: 'Clear',
    hideWindow: 'Hide window',
    language: 'Language',
    archive: 'Archive',
    unarchive: 'Unarchive',
    pinNote: 'Pin note',
    unpinNote: 'Unpin note',
    markDone: 'Mark done',
    markUndone: 'Mark undone',
    overlayClickThrough: 'Enable sticker global control',
    overlayClose: 'Close overlay',
    overlayTip: 'Use Ctrl+Shift+O or tray to toggle global control mode',
    trayShowMain: 'Show main window',
    trayShowNotes: 'Show main window',
    trayGithub: 'Star on GitHub',
    trayStickiesClose: 'Overlay: Close',
    trayStickiesShow: 'Desktop overlay',
    trayInteraction: 'Stickers: Toggle global control',
    trayInteractionStateOn: 'Sticker global control: ON',
    trayInteractionStateOff: 'Sticker global control: OFF',
    trayQuit: 'Exit',
    glassAdjust: 'Scroll to adjust opacity',
    sortByCustom: 'Manual',
    sortByNewest: 'Newest',
    sortByOldest: 'Oldest',
    sortMode: 'Sort',
    trash: 'Trash',
    restore: 'Restore',
    permanentlyDelete: 'Permanent delete',
    emptyTrash: 'Empty trash',
    pinToTop: 'Always on Top',
    pinToBottom: 'Pin to Bottom',
    pinToWallpaper: 'Wallpaper layer',
    pinToDesktopLayer: 'Desktop layer',
    frost: 'Frost',
    textColor: 'Text color',
    customColor: 'Custom',
    dragToReorder: 'Drag to reorder',
    priority: 'Tag',
    quadrantTag: 'Tag',
    tags: 'Tags',
    tagsPlaceholder: 'Type tag + Enter',
    priorityUnassigned: 'No tag',
    quadrantQ1: 'Q1 Important + Urgent',
    quadrantQ2: 'Q2 Important + Not Urgent',
    quadrantQ3: 'Q3 Urgent + Not Important',
    quadrantQ4: 'Q4 Routine / Later',
    quadrantQ1Desc: 'Do first',
    quadrantQ2Desc: 'Schedule',
    quadrantQ3Desc: 'Delegate / fast handle',
    quadrantQ4Desc: 'Backlog',
    emptyInQuadrant: 'No notes in this quadrant',
    emptyActiveTitle: 'No notes yet',
    emptyActiveHint: 'Type above and press Enter to create one',
    emptyArchivedTitle: 'No archived notes',
    emptyTrashTitle: 'Trash is empty',
    emptySearchTitle: 'No matching notes',
    emptySearchHint: 'Try a different keyword',
    noteLoading: 'Loading…',
    noteExternalChange: 'This note changed elsewhere. Your draft is preserved and has not been saved.',
    noteReloadExternal: 'Reload',
    noteFinishEditing: 'Finish editing',
    noteToolbar: 'Note actions',
    noteEditBlock: 'Edit block',
    noteAddSameBlock: 'Add another block of this type',
    noteImagePasteError: 'The image could not be pasted. Your text draft is unchanged.',
    changeColor: 'Note color',
    settings: 'Settings',
    workspaceBrandTag: 'WORKSPACE',
    workspaceTitle: 'Workspace',
    workspaceModules: 'Navigation',
    workspaceTabNotes: 'Notes',
    workspaceTabFocus: 'Focus',
    workspaceTabReview: 'Review',
    workspaceNoteFilters: 'Views',
    workspaceReviewSidebarTitle: 'Review',
    workspaceReviewSidebarHint:
      'Review is the results layer for what you finished, when it happened, and how recent focus turns into visible progress.',
    workspaceReviewTabLog: 'Done',
    workspaceReviewTabCalendar: 'Calendar',
    workspaceReviewTabStats: 'Stats',
    workspaceReviewSummaryTodayFocus: 'Today focus',
    workspaceReviewSummaryTodayDone: 'Today done',
    workspaceReviewSummaryWeekDone: 'This week done',
    workspaceReviewSummaryStreak: 'Record streak',
    workspaceReviewStageBadge: 'MVP',
    workspaceReviewLogBadge: 'Recent done',
    workspaceReviewLogTitle: 'Done timeline',
    workspaceReviewLogBody:
      'This timeline is for browsing what you finished recently. If you need to fill in something outside the main flow, create a backfilled done item and set when it was completed.',
    workspaceReviewCreatePlaceholder: 'Describe what you finished...',
    workspaceReviewCreateAction: 'Backfill done item',
    workspaceReviewDraftTitle: 'Backfill a done item',
    workspaceReviewDraftHint: 'Create the item inside the timeline and set its actual completion time so Review and Calendar stay aligned.',
    workspaceReviewDraftContentLabel: 'What got done',
    workspaceReviewDraftCompletedAtLabel: 'Completed at',
    workspaceReviewDraftSaveAction: 'Save done item',
    workspaceReviewLogEmptyTitle: 'No done items yet',
    workspaceReviewLogEmptyBody:
      'Complete a task or mark a note as done, and it will appear here automatically and on the calendar for that day.',
    workspaceReviewLogFilteredEmptyTitle: 'No matching done items',
    workspaceReviewLogFilteredEmptyBody:
      'Try broadening the time range, changing the selected tag, or searching with another keyword.',
    workspaceReviewFiltersSearchLabel: 'Search',
    workspaceReviewFiltersSearchPlaceholder: 'Search done items, notes, or tags...',
    workspaceReviewFiltersRangeLabel: 'Time range',
    workspaceReviewFiltersRangeAll: 'All time',
    workspaceReviewFiltersRangeToday: 'Today',
    workspaceReviewFiltersRangeLast7Days: 'Last 7 days',
    workspaceReviewFiltersRangeLast30Days: 'Last 30 days',
    workspaceReviewFiltersRangeThisMonth: 'This month',
    workspaceReviewFiltersTagLabel: 'Tag',
    workspaceReviewFiltersTagAll: 'All tags',
    workspaceReviewFiltersActive: 'Filtered',
    workspaceReviewFiltersResultCountSuffix: 'matches',
    workspaceReviewFiltersClear: 'Clear filters',
    workspaceReviewCalendarBadge: 'By day',
    workspaceReviewCalendarPrev: 'Previous',
    workspaceReviewCalendarNext: 'Next',
    workspaceReviewCalendarToday: 'Today',
    workspaceReviewCalendarCountSuffix: 'done',
    workspaceReviewCalendarEmptyCount: 'No records',
    workspaceReviewCalendarTitle: 'Calendar review',
    workspaceReviewCalendarBody:
      'The first calendar version already groups completed notes by day, so you can review your visible trail instead of facing a plain to-do list.',
    workspaceReviewStatsTitle: 'Focus stats',
    workspaceReviewStatsBody:
      'Review focus input, daily rhythm, and task distribution here so effort and visible output stay in the same conversation.',
    workspaceReviewLogInspectorTitle: 'Done details',
    workspaceReviewLogInspectorBody:
      'Select a done item to view its completion time, summary, tags, and source here.',
    workspaceReviewCalendarInspectorTitle: 'Day details',
    workspaceReviewCalendarInspectorBody:
      'When you click a date on the calendar, this side will show all records from that day for continuous review.',
    workspaceReviewCalendarInspectorSelectedBody:
      'These records were completed on the selected day. Open any one to continue editing or reviewing its full content.',
    workspaceReviewCalendarInspectorEmptyTitle: 'No records on this day',
    workspaceReviewCalendarInspectorEmptyBody:
      'This day does not have completed notes yet. Move through the month to review where the real output clustered.',
    workspaceReviewStatsInspectorTitle: 'Stats notes',
    workspaceReviewStatsInspectorBody:
      'Use this side as a reading guide: stats should help you see how much you invested, how steady your rhythm was, and whether that effort turned into visible output.',
    workspaceReviewStatsHelpTip:
      'Stats show focus input and rhythm. Pair them with Done and Calendar to judge whether the effort became visible output.',
    workspaceReviewStatsExplainerInputTitle: 'Input',
    workspaceReviewStatsExplainerInputBody:
      'Today focus, 7-day focus, and streak answer the first question: how much time and continuity did you really put in recently?',
    workspaceReviewStatsExplainerRhythmTitle: 'Rhythm',
    workspaceReviewStatsExplainerRhythmBody:
      'Pomodoros, heatmap, and task distribution reveal whether recent work was steady, fragmented, or concentrated on only a few tasks.',
    workspaceReviewStatsExplainerOutputTitle: 'Output link',
    workspaceReviewStatsExplainerOutputBody:
      'Stats alone only show effort. Pair them with Done and Calendar to judge whether that effort actually turned into concrete results.',
    workspaceReviewOpenCalendarDay: 'View that day',
    workspaceReviewOpenSource: 'Open source note',
    workspaceReviewRecordSourceDoneLog: 'Done log',
    workspaceReviewRecordSourceDoneNote: 'Done note',
    workspaceReviewCurrentPhase: 'Current phase',
    workspaceReviewCurrentPhaseBody:
      'Review now combines done timeline, calendar, and stats in one place.',
    workspaceFocusReviewCardTitle: 'Review lives here now',
    workspaceFocusReviewCardHint:
      'Focus keeps the runtime controls. Full heatmaps, distributions, and retrospective stats move into Review so execution and results stay clearly separated.',
    workspaceFocusOpenReview: 'Open Review',
    workspaceFocusDoneLogPromptTitle: 'Save this focus result to Review',
    workspaceFocusDoneLogPromptHint:
      'This prompt only appears when the current task first reaches its target, so Review records stay meaningful instead of becoming noisy.',
    workspaceFocusDoneLogDraftLine: 'Completed one focus session.',
    workspaceFocusDoneLogDraftMinutes: 'Focus minutes',
    workspaceFocusDoneLogDraftPomodoros: 'Task pomodoros today',
    workspaceFocusDoneLogDraftTaskFocus: 'Task focus total',
    workspaceFocusDoneLogDraftTaskWindow: 'Task window',
    workspaceFocusDoneLogDraftTaskWindowSeparator: ' - ',
    workspaceTodoView: 'Todo (open)',
    workspaceTagsFilter: 'Tag filter',
    workspaceTagsAll: 'All tags',
    workspaceTagsEmpty: 'No tags in this view',
    workspaceCreateTag: 'Create tag',
    workspaceInitialView: 'Startup view',
    workspaceInitialViewLast: 'Last used',
    workspaceDisplayScale: 'Display scale',
    workspaceDisplayScaleAuto: 'Auto',
    workspaceFontSize: 'Font size',
    workspaceFontSizeSmall: 'Small',
    workspaceFontSizeMedium: 'Medium',
    workspaceFontSizeLarge: 'Large',
    workspaceThemePreset: 'Theme preset',
    workspaceThemePresetLight: 'Sky light',
    workspaceThemePresetDark: 'Midnight blue',
    workspaceThemePresetPaper: 'Paper ivory',
    workspaceThemePresetForest: 'Forest night',
    workspaceThemePresetSunset: 'Sunset bloom',
    workspaceThemeCustomCss: 'Custom theme',
    workspaceThemeCustomCssPlaceholder: 'Click "Copy full template", then paste and edit by module.',
    workspaceThemeCustomCssHint: 'Supports complete component-level overrides. Applied immediately and saved automatically.',
    workspaceThemeExport: 'Export theme',
    workspaceThemeImport: 'Import theme',
    workspaceThemeImportSuccess: 'Theme imported',
    workspaceThemeImportFailed: 'Import failed',
    workspaceThemeImportInvalid: 'Invalid theme content',
    workspaceThemeCopyDefault: 'Copy full template',
    workspaceThemeCopyDefaultSuccess: 'Default template copied',
    workspaceThemeCopyDefaultFailed: 'Copy failed',
    workspaceThemeTransitionStyle: 'Theme transition',
    workspaceThemeTransitionStyleHint: 'Choose how the workstation theme spreads when switching light and dark.',
    workspaceSidebarLayoutMode: 'Sidebar layout',
    workspaceSidebarLayoutAuto: 'Auto priority',
    workspaceSidebarLayoutManual: 'Manual resize',
    workspaceSidebarManualResizeHint: 'Drag to resize navigation and task sections',
    workspaceFocusHint: 'Focus planning and pomodoro',
    workspaceDeadlineTitle: 'Deadlines today',
    workspaceDeadlineEmpty: 'No pending deadlines',
    workspaceDeadlineOverdue: 'Overdue',
    workspaceDeadlineStartsIn: 'Starts in',
    workspaceDeadlineDueIn: 'Due in',
    workspaceDeadlineStateRunning: 'Running',
    workspaceDeadlineStateUpcoming: 'Upcoming',
    workspaceDeadlineStateOverdue: 'Overdue',
    workspaceDeadlineStateCompleted: 'Completed',
    workspaceDeadlineActionView: 'View',
    workspaceDeadlineActionStart: 'Start',
    workspaceDeadlineActionSnooze15: '+15m',
    workspaceDeadlineActionSnooze30: '+30m',
    details: 'Details',
    openDetails: 'Open details',
    minimizeWindow: 'Minimize window',
    maximizeWindow: 'Maximize window',
    restoreWindow: 'Restore window',
    themeTransitionCircle: 'Circle wipe',
    themeTransitionHeart: 'Soft bloom',
    workspaceHint: 'Notes, tasks and focus in one place',
    switchToWorkspace: 'Open workspace',
    switchToCompact: 'Compact mode',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
    themeLight: 'Light mode',
    themeDark: 'Dark mode',
    settingsTitle: 'Settings',
    starOnGithub: 'Star on GitHub',
    general: 'General',
    autoStart: 'Start on Boot',
    showPanelOnStartup: 'Show panel on startup',
    markdownStorageTitle: 'Storage & Interop',
    markdownStorageModeLabel: 'Markdown storage mode',
    markdownStorageModeHint: 'Keep Markdown files in the app default directory or point to an external workspace like an Obsidian vault.',
    markdownStorageModeAppDefault: 'App default directory',
    markdownStorageModeCustomDirectory: 'Custom directory',
    markdownStorageRootLabel: 'Custom Markdown directory',
    markdownStorageRootHint: 'Paste a folder path. We will create notes / review / attachments under it if needed.',
    markdownStorageRootPlaceholder: '/path/to/your/markdown/workspace',
    markdownStorageResolvedRootLabel: 'Resolved storage root',
    markdownStorageResolvedRootHint: 'This is the actual root directory the app will use for future Markdown files.',
    markdownStorageStatusReady: 'Ready',
    markdownStorageStatusMissing: 'Will create',
    markdownStorageApply: 'Apply storage path',
    markdownStorageApplying: 'Applying...',
    markdownStorageApplySuccess: 'Markdown storage updated.',
    markdownStorageExport: 'Export Markdown',
    markdownStorageExporting: 'Exporting...',
    markdownStorageExportSuccess:
      'Exported {count} Markdown files to the storage workspace and copied {attachments} attachments.',
    markdownStorageImport: 'Import Markdown',
    markdownStorageImporting: 'Importing...',
    markdownStorageImportSuccess:
      'Imported {imported} Markdown files, updated {updated} existing files, and restored {attachments} attachments.',
    markdownStorageImportPreviewFailed: 'Failed to preview Markdown import.',
    markdownStorageImportPreviewEmpty: 'No Markdown files were found under notes/ or review/.',
    markdownStorageImportCancelled: 'Markdown import cancelled.',
    markdownStorageImportPreviewConfirm:
      'Markdown import preview:\\n- scanned: {scanned}\\n- new files: {import}\\n- files to update: {update}\\n- attachments to restore: {attachments}\\n- files without note_id: {withoutId}\\n\\nContinue import?',
    proMode: 'Hide Hints',
    showStickyToggleOnHome: 'Pin stickers control to header',
    shortcuts: 'Shortcuts',
    shortcutToggle: 'Toggle Panel: Ctrl+Shift+N',
    shortcutOverlay: 'Toggle global control: Ctrl+Shift+O',
    shortcutStickyHide: 'Hide/reveal top sticky: Ctrl+Shift+H',
    shortcutToggleLabel: 'Toggle panel',
    shortcutOverlayLabel: 'Toggle global control',
    shortcutStickyHideLabel: 'Hide/reveal sticky',
    shortcutFormatHint: 'Use accelerator format like Ctrl+Shift+N. Leave empty to disable a shortcut.',
    shortcutApply: 'Apply',
    shortcutSaving: 'Saving...',
    shortcutStatusRegistered: 'Registered',
    shortcutStatusPending: 'Pending',
    shortcutStatusConflict: 'Conflict: already used by another app or action',
    shortcutStatusInvalid: 'Invalid shortcut format',
    shortcutStatusDisabled: 'Disabled',
    shortcutStatusError: 'Registration failed',
    shortcutStatusRegisteredHint: 'This shortcut is registered successfully and will respond globally.',
    shortcutStatusPendingHint: 'You changed the value, but it has not been applied yet. The previous shortcut is still active.',
    shortcutStatusConflictHint: 'This shortcut could not be registered because it conflicts with another app or another action.',
    shortcutStatusInvalidHint: 'The format is invalid. Use a value like Ctrl+Shift+N.',
    shortcutStatusDisabledHint: 'This action has no global shortcut. Leave it empty if you want to keep it disabled.',
    shortcutStatusErrorHint: 'Registration failed for another reason. Hover to see the runtime error message if available.',
    shortcutEsc: 'Hide/Exit Interaction: Escape',
    shortcutPinSave: 'Pin & Save: Ctrl+Enter',
    version: 'Version v1.0.0',
    close: 'Close',
    notesStorageRecoveryTitle: 'Notes need recovery',
    notesStorageRecoveryBody:
      'The notes data file could not be read, so writing is disabled to protect the existing data.',
    openNotesDataDirectory: 'Open data directory',
    feedbackCommunityEyebrow: 'Feedback',
    feedbackCommunityTitle: 'Community group',
    feedbackCommunityHint: 'Scan the QR code to join the group for feedback, bug reports, and product ideas.',
    feedbackCommunityCaption: 'Join the group to share issues, ideas, and usage feedback.',
    feedbackCommunityDevCaption: 'Visible in packaged builds too.',
    noteEditorPlaceholder: 'Write here. Markdown is supported.',
    noteOpacityHud: 'Opacity',
    noteFrostHud: 'Frost',
    stickyAutoHideEnable: 'Enable edge auto hide',
    stickyAutoHideDisable: 'Disable edge auto hide',
    workspaceQuickNoteHint: 'Type and press Enter to quick-create, or click + New note.',
    workspaceCreateNote: 'New note',
    pomodoro: 'Pomodoro',
    pomodoroFocus: 'Focus',
    pomodoroShortBreak: 'Short break',
    pomodoroLongBreak: 'Long break',
    pomodoroRound: 'Round',
    pomodoroTask: 'Task',
    pomodoroTaskElapsed: 'Elapsed',
    pomodoroTaskCompleted: 'Completed',
    pomodoroTasksCompleted: 'Tasks reached target',
    pomodoroTaskRounds: 'Task rounds',
    pomodoroTaskCurrentRound: 'Current round',
    pomodoroTaskModeDuration: 'Duration',
    pomodoroTaskModeTimeWindow: 'Time window',
    pomodoroTaskTargetMinutes: 'Target minutes',
    pomodoroTaskFlexibleSchedule: 'Flexible schedule',
    pomodoroTaskPlanner: 'Focus Planner',
    pomodoroTaskTitle: 'Task title',
    pomodoroNoTaskSelected: 'Not selected',
    pomodoroNoTasksToday: 'No focus tasks for today',
    pomodoroTaskRollup: 'Task totals',
    pomodoroCompletedSessions: 'Completed sessions',
    pomodoroTaskSettingsTitle: 'Pomodoro task settings',
    pomodoroTaskSettingsHint: 'Only keeps task-start reminder settings here.',
    pomodoroStats: 'Stats',
    pomodoroTodayFocusMinutes: 'Today focus',
    pomodoroTodayPomodoros: 'Today total pomodoros',
    pomodoroTodayPomodorosHint: 'Counts completed pomodoros today (all tasks). Per-task counts are shown in the task list.',
    pomodoroFocusMinutesHint: 'A pomodoro is counted after this full duration completes. Changes apply to new cycles.',
    pomodoroWeekFocusMinutes: 'Last 7 days focus',
    pomodoroWeekPomodoros: 'Last 7 days sessions',
    pomodoroWeekAverageMinutes: '7-day average',
    pomodoroStreakDays: 'Streak',
    pomodoroBestDay: 'Best day',
    pomodoroHeatmap28Days: 'Last 28 days heatmap',
    pomodoroTaskDistributionToday: 'Today task distribution',
    pomodoroStart: 'Start',
    pomodoroResume: 'Resume',
    pomodoroPause: 'Pause',
    pomodoroSkip: 'Skip',
    pomodoroFocusMinutes: 'Pomodoro duration (min)',
    pomodoroShortBreakMinutes: 'Short break (min)',
    pomodoroLongBreakMinutes: 'Long break (min)',
    pomodoroLongBreakEvery: 'Long break every',
    pomodoroMiniBreakEveryMinutes: 'Mini break every (min)',
    pomodoroMiniBreakDurationSeconds: 'Mini break duration (sec)',
    pomodoroLongBreakEveryMinutes: 'Long break every (min)',
    pomodoroLongBreakDurationMinutes: 'Long break duration (min)',
    pomodoroBreakNotifyBeforeSeconds: 'Notify before (sec)',
    pomodoroMiniBreakIn: 'Mini break in',
    pomodoroLongBreakIn: 'Long break in',
    pomodoroBreakNotifyStatus: 'Notify',
    pomodoroBreakNotifyOn: 'On',
    pomodoroBreakNotifyOff: 'Off',
    pomodoroBreakActionPanel: 'Break controls',
    pomodoroBreakRunning: 'Break countdown running',
    pomodoroBreakPostponeTwoMinutes: 'Postpone 2m',
    pomodoroBreakRemaining: 'Remaining',
    pomodoroBreakStartNow: 'Start break',
    pomodoroBreakWaitState: 'Waiting for break trigger',
    pomodoroBreakActionHint: 'Enable reminders to trigger mini/long break prompts at your configured intervals.',
    pomodoroBreakSessionActive: 'Global break pause',
    pomodoroBreakSessionNone: 'No global pause',
    pomodoroBreakSession30m: '30m',
    pomodoroBreakSession1h: '1h',
    pomodoroBreakSession2h: '2h',
    pomodoroBreakSessionToday: 'Today',
    pomodoroBreakSessionClear: 'Clear',
    pomodoroBreakControlEnable: 'Enable reminders',
    pomodoroBreakControlDisable: 'Disable reminders',
    pomodoroBreakToggleLabel: 'Break reminder switch',
    pomodoroToggleOff: 'Off',
    pomodoroToggleOn: 'On',
    pomodoroBreakPausePreset: 'Pause preset',
    pomodoroBreakReminderMode: 'Reminder style',
    pomodoroBreakReminderModeFullscreen: 'Full-screen reminder',
    pomodoroBreakReminderModePanel: 'Light reminder',
    pomodoroBreakReminderModeFullscreenHint: 'Show a full-screen break prompt in current workspace window.',
    pomodoroBreakReminderModePanelHint: 'Show a light reminder card without taking over the whole window.',
    pomodoroBreakReminderEnabled: 'Break reminders enabled',
    pomodoroBreakReminderDisabled: 'Break reminders disabled',
    pomodoroBreakSessionScopeGlobal: 'Independent',
    pomodoroBreakSessionScopeTask: 'Bind task',
    pomodoroBreakSessionBindTaskHint: 'Select a task first to start task-bound session.',
    pomodoroBreakSessionIndependentHint: 'Run independently, no task binding',
    pomodoroBreakScheduleSourceIndependent: 'Independent interval',
    pomodoroBreakScheduleTaskResolved: 'Current task cadence',
    pomodoroBreakScheduleIndependentMini: 'Independent mini every (min)',
    pomodoroBreakScheduleIndependentLong: 'Independent long every (min)',
    pomodoroBreakQuickTest: 'Quick test',
    pomodoroBreakQuickMini10s: 'Mini 10s',
    pomodoroBreakQuickLong10s: 'Long 10s',
    pomodoroMiniBreakSoon: 'Mini break soon',
    pomodoroLongBreakSoon: 'Long break soon',
    pomodoroMiniBreakNow: 'Take a mini break',
    pomodoroLongBreakNow: 'Take a long break',
    pomodoroBreakIn: 'Break in',
    pomodoroBreakDuration: 'Duration',
    pomodoroTaskStartSoon: 'Task starts soon',
    pomodoroTaskStartAt: 'Starts at',
    pomodoroTaskStartLead: 'In',
    pomodoroBreakNotifyHint: 'Desktop notification permission is required for break reminders.',
    pomodoroTaskStartReminderToggle: 'Task start reminder',
    pomodoroTaskStartReminderLeadMinutes: 'Remind before task start (min)',
    pomodoroTaskReminderDefaultLeadMinutes: 'Default reminder lead time (min)',
    workspaceRecoverPinnedStickiesTitle: 'Recover pinned stickies',
    workspaceRecoverPinnedStickiesHint:
      'If a sticky was dragged off-screen, bring all pinned stickies back into the primary monitor.',
    workspaceRecoverPinnedStickiesAction: 'Recover now',
    workspaceRecoverPinnedStickiesRunning: 'Recovering...',
    pomodoroTaskReminderQuickTest: 'Reminder test',
    pomodoroTaskReminderQuickNow: 'Trigger now',
    pomodoroMiniBreakPostponeMinutes: 'Mini postpone (min)',
    pomodoroLongBreakPostponeMinutes: 'Long postpone (min)',
    pomodoroBreakPostponeLimit: 'Postpone limit',
    pomodoroBreakStrictMode: 'Strict mode',
    workspacePlannerShowingAllHint: 'No tasks match today. Showing all tasks.',
    workspacePlannerTodayMatched: 'Today matched',
    workspaceFocusEditSettings: 'Edit settings',
    workspaceFocusHideSettings: 'Hide settings',
    workspaceMultiScreenHint: 'This prompt follows current workspace window on multi-screen setup.',
    recurrenceNone: 'Once',
    recurrenceDaily: 'Daily',
    recurrenceWorkday: 'Workdays',
    recurrenceCustom: 'Custom',
    addTask: 'Add task',
    weekdayMon: 'Mon',
    weekdayTue: 'Tue',
    weekdayWed: 'Wed',
    weekdayThu: 'Thu',
    weekdayFri: 'Fri',
    weekdaySat: 'Sat',
    weekdaySun: 'Sun'
  },
  zh: {
    appName: 'Desk Tidy 便笺',
    inputHint: '输入便笺…（回车保存）',
    saveNote: '保存',
    saveNoteAction: '保存便笺',
    cancel: '取消',
    hideAfterSave: '保存后隐藏主界面',
    compactActive: '活动',
    active: '全部',
    todo: '待办',
    quadrant: '四象限',
    archived: '已归档',
    overlay: '启用桌面贴纸',
    searchHint: '搜索（支持拼音）…',
    edit: '编辑',
    delete: '删除',
    clear: '清除',
    hideWindow: '隐藏窗口',
    language: '语言',
    archive: '归档',
    unarchive: '恢复',
    pinNote: '钉住便笺',
    unpinNote: '取消钉住',
    markDone: '标记完成',
    markUndone: '取消完成',
    overlayClickThrough: '启用贴纸全局操作',
    overlayClose: '关闭贴纸',
    overlayTip: '用 Ctrl+Shift+O 或托盘切换全局操作模式',
    trayShowMain: '显示主窗口',
    trayShowNotes: '显示主窗口',
    trayGithub: '在 GitHub 上点星',
    trayStickiesClose: '贴纸：关闭',
    trayStickiesShow: '桌面贴纸',
    trayInteraction: '贴纸：切换全局操作',
    trayInteractionStateOn: '贴纸全局操作：开',
    trayInteractionStateOff: '贴纸全局操作：关',
    trayQuit: '退出',
    glassAdjust: '滚轮调节透明度',
    sortByCustom: '手动',
    sortByNewest: '最新',
    sortByOldest: '最早',
    sortMode: '排序',
    trash: '回收站',
    restore: '恢复',
    permanentlyDelete: '永久删除',
    emptyTrash: '清空回收站',
    pinToTop: '置顶显示',
    pinToBottom: '贴在底部',
    pinToWallpaper: '贴到壁纸层',
    pinToDesktopLayer: '贴在图标上层',
    frost: '磨砂',
    textColor: '文字颜色',
    customColor: '自定义',
    dragToReorder: '拖动排序',
    priority: '标签',
    quadrantTag: '标签',
    tags: '标签',
    tagsPlaceholder: '输入标签后回车',
    priorityUnassigned: '无标签',
    quadrantQ1: 'Q1 重要且紧急',
    quadrantQ2: 'Q2 重要不紧急',
    quadrantQ3: 'Q3 紧急不重要',
    quadrantQ4: 'Q4 常规/稍后',
    quadrantQ1Desc: '优先处理',
    quadrantQ2Desc: '计划推进',
    quadrantQ3Desc: '快速处理/委派',
    quadrantQ4Desc: '积压池',
    emptyInQuadrant: '该象限暂无事项',
    emptyActiveTitle: '还没有便笺',
    emptyActiveHint: '在上方输入内容，回车即可创建',
    emptyArchivedTitle: '暂无归档便笺',
    emptyTrashTitle: '回收站是空的',
    emptySearchTitle: '没有匹配的便笺',
    emptySearchHint: '换个关键词试试',
    noteLoading: '加载中…',
    noteExternalChange: '此便笺已在其他窗口更新。当前草稿已保留，但尚未保存。',
    noteReloadExternal: '重新加载',
    noteFinishEditing: '完成编辑',
    noteToolbar: '便笺操作',
    noteEditBlock: '编辑此块',
    noteAddSameBlock: '添加同类型内容块',
    noteImagePasteError: '图片粘贴失败，当前文字草稿未受影响。',
    changeColor: '便笺颜色',
    settings: '设置',
    workspaceBrandTag: 'WORKSPACE',
    workspaceTitle: '工作台',
    workspaceModules: '导航',
    workspaceTabNotes: '笔记',
    workspaceTabFocus: '专注',
    workspaceTabReview: '回顾',
    workspaceNoteFilters: '视图',
    workspaceReviewSidebarTitle: '回顾',
    workspaceReviewSidebarHint: '回顾是工作台的结果层：看做了什么、哪天做的，以及专注投入如何变成可见成果。',
    workspaceReviewTabLog: '已办',
    workspaceReviewTabCalendar: '日历',
    workspaceReviewTabStats: '统计',
    workspaceReviewSummaryTodayFocus: '今日专注',
    workspaceReviewSummaryTodayDone: '今日已办',
    workspaceReviewSummaryWeekDone: '本周已办',
    workspaceReviewSummaryStreak: '连续记录',
    workspaceReviewStageBadge: 'MVP',
    workspaceReviewLogBadge: '最近完成',
    workspaceReviewLogTitle: '已办时间线',
    workspaceReviewLogBody:
      '这里先看最近完成了什么。只有当某件事发生在主流程之外时，再补记一条已办，并把真正的完成时间补上。',
    workspaceReviewCreatePlaceholder: '写下你完成了什么…',
    workspaceReviewCreateAction: '补记已办',
    workspaceReviewDraftTitle: '补记一条已办',
    workspaceReviewDraftHint: '补记卡会直接插入时间线里，同时把真实完成时间写清楚，避免回顾和日历失真。',
    workspaceReviewDraftContentLabel: '做成了什么',
    workspaceReviewDraftCompletedAtLabel: '完成时间',
    workspaceReviewDraftSaveAction: '保存到已办',
    workspaceReviewLogEmptyTitle: '还没有已办',
    workspaceReviewLogEmptyBody:
      '完成一条任务，或把一条笔记标记为完成后，它会自动出现在这里，并同步到对应日期的日历里。',
    workspaceReviewLogFilteredEmptyTitle: '当前筛选下还没有结果',
    workspaceReviewLogFilteredEmptyBody:
      '可以试着放宽时间范围、切换标签，或换一个关键词继续找。',
    workspaceReviewFiltersSearchLabel: '搜索',
    workspaceReviewFiltersSearchPlaceholder: '搜索已办内容、笔记正文或标签…',
    workspaceReviewFiltersRangeLabel: '时间范围',
    workspaceReviewFiltersRangeAll: '全部时间',
    workspaceReviewFiltersRangeToday: '今天',
    workspaceReviewFiltersRangeLast7Days: '最近 7 天',
    workspaceReviewFiltersRangeLast30Days: '最近 30 天',
    workspaceReviewFiltersRangeThisMonth: '本月',
    workspaceReviewFiltersTagLabel: '标签',
    workspaceReviewFiltersTagAll: '全部标签',
    workspaceReviewFiltersActive: '筛选中',
    workspaceReviewFiltersResultCountSuffix: '条匹配',
    workspaceReviewFiltersClear: '清空筛选',
    workspaceReviewCalendarBadge: '按天回看',
    workspaceReviewCalendarPrev: '上个月',
    workspaceReviewCalendarNext: '下个月',
    workspaceReviewCalendarToday: '今天',
    workspaceReviewCalendarCountSuffix: '条',
    workspaceReviewCalendarEmptyCount: '暂无',
    workspaceReviewCalendarTitle: '日历回看',
    workspaceReviewCalendarBody:
      '第一版日历已经会按天聚合已完成记录，让你能看到哪几天真正产出了结果，而不是只面对一份持续施压的待办清单。',
    workspaceReviewStatsTitle: '专注统计',
    workspaceReviewStatsBody:
      '这里先看投入、节奏和任务分布，再和已办、日历放在一起看，判断最近的忙碌到底有没有变成真实产出。',
    workspaceReviewLogInspectorTitle: '已办详情',
    workspaceReviewLogInspectorBody:
      '选中一条已办后，这里会展示它的完成时间、内容摘要、标签和来源，方便继续回看。',
    workspaceReviewCalendarInspectorTitle: '日期详情',
    workspaceReviewCalendarInspectorBody:
      '点击日历中的某一天后，这里会展示当天的全部记录，支持继续进入单条内容。',
    workspaceReviewCalendarInspectorSelectedBody:
      '这些是你在所选日期完成的记录。你可以继续打开单条内容，回看当时到底做成了什么。',
    workspaceReviewCalendarInspectorEmptyTitle: '这一天还没有记录',
    workspaceReviewCalendarInspectorEmptyBody:
      '这一天暂时没有已完成记录。继续翻月份和日期，就能看见产出更集中的时间段。',
    workspaceReviewStatsInspectorTitle: '统计说明',
    workspaceReviewStatsInspectorBody:
      '把这里当成一张读图说明卡：统计不是单纯堆数字，而是帮你看清最近投入了多少、节奏是否稳定，以及这些投入有没有变成真实结果。',
    workspaceReviewStatsHelpTip:
      '统计用于看专注投入和节奏稳定性；结合已办和日历，才能判断这些投入有没有形成产出。',
    workspaceReviewStatsExplainerInputTitle: '看投入',
    workspaceReviewStatsExplainerInputBody:
      '今日专注、近 7 天专注和连续天数先回答一个问题：你最近到底投入了多少时间，而且这种投入是不是连续的。',
    workspaceReviewStatsExplainerRhythmTitle: '看节奏',
    workspaceReviewStatsExplainerRhythmBody:
      '番茄数、热力图和任务分布用来判断节奏是不是稳定，是持续推进，还是被很多零碎任务切碎了。',
    workspaceReviewStatsExplainerOutputTitle: '看结果联动',
    workspaceReviewStatsExplainerOutputBody:
      '统计本身只说明投入，不说明产出。要结合已办和日历一起看，才能判断这些投入有没有真的沉淀成结果。',
    workspaceReviewOpenCalendarDay: '查看当天',
    workspaceReviewOpenSource: '打开原笔记',
    workspaceReviewRecordSourceDoneLog: '已办记录',
    workspaceReviewRecordSourceDoneNote: '已完成笔记',
    workspaceReviewCurrentPhase: '当前阶段',
    workspaceReviewCurrentPhaseBody:
      '回顾现在会把已办、日历和统计放在一起，方便按结果回看今天真正做成了什么。',
    workspaceFocusReviewCardTitle: '完整回顾已经搬过去了',
    workspaceFocusReviewCardHint:
      '专注页现在只保留运行控制和轻量摘要。完整热力图、任务分布和复盘统计统一放到“回顾”里查看。',
    workspaceFocusOpenReview: '打开回顾',
    workspaceFocusDoneLogPromptTitle: '把这次专注结果记到回顾里',
    workspaceFocusDoneLogPromptHint:
      '这里只会在当前任务第一次达成目标时提醒，避免每轮专注都弹一次，把回顾页变得太吵。',
    workspaceFocusDoneLogDraftLine: '完成了一次专注轮次。',
    workspaceFocusDoneLogDraftMinutes: '专注时长',
    workspaceFocusDoneLogDraftPomodoros: '该任务今日番茄数',
    workspaceFocusDoneLogDraftTaskFocus: '该任务累计专注',
    workspaceFocusDoneLogDraftTaskWindow: '任务时间窗',
    workspaceFocusDoneLogDraftTaskWindowSeparator: ' - ',
    workspaceTodoView: '待办（未完成）',
    workspaceTagsFilter: '标签筛选',
    workspaceTagsAll: '全部标签',
    workspaceTagsEmpty: '当前视图暂无标签',
    workspaceCreateTag: '新建标签',
    workspaceInitialView: '初始视图',
    workspaceInitialViewLast: '跟随上次',
    workspaceDisplayScale: '显示缩放',
    workspaceDisplayScaleAuto: '自适应',
    workspaceFontSize: '字体大小',
    workspaceFontSizeSmall: '小',
    workspaceFontSizeMedium: '标准',
    workspaceFontSizeLarge: '大',
    workspaceThemePreset: '主题预设',
    workspaceThemePresetLight: '浅色·天空',
    workspaceThemePresetDark: '深色·午夜',
    workspaceThemePresetPaper: '米白纸感',
    workspaceThemePresetForest: '森林夜色',
    workspaceThemePresetSunset: '晚霞柔光',
    workspaceThemeCustomCss: '自定义主题',
    workspaceThemeCustomCssPlaceholder: '先点“复制完整模板”，再粘贴后按模块修改。',
    workspaceThemeCustomCssHint: '支持完整组件级覆写，实时生效并自动保存。',
    workspaceThemeExport: '导出主题',
    workspaceThemeImport: '导入主题',
    workspaceThemeImportSuccess: '主题导入成功',
    workspaceThemeImportFailed: '导入失败',
    workspaceThemeImportInvalid: '主题内容无效',
    workspaceThemeCopyDefault: '复制完整模板',
    workspaceThemeCopyDefaultSuccess: '默认模板已复制',
    workspaceThemeCopyDefaultFailed: '复制失败',
    workspaceThemeTransitionStyle: '主题切换动效',
    workspaceThemeTransitionStyleHint: '选择工作台在明暗主题切换时的扩散方式。',
    workspaceSidebarLayoutMode: '侧栏布局',
    workspaceSidebarLayoutAuto: '自动优先',
    workspaceSidebarLayoutManual: '手动拖拽',
    workspaceSidebarManualResizeHint: '拖拽分隔线调整导航与任务分区高度',
    workspaceFocusHint: '专注任务与番茄规划',
    workspaceDeadlineTitle: '今日任务',
    workspaceDeadlineEmpty: '暂无待截止任务',
    workspaceDeadlineOverdue: '已超时',
    workspaceDeadlineStartsIn: '开始于',
    workspaceDeadlineDueIn: '剩余',
    workspaceDeadlineStateRunning: '进行中',
    workspaceDeadlineStateUpcoming: '待开始',
    workspaceDeadlineStateOverdue: '已超时',
    workspaceDeadlineStateCompleted: '已达标',
    workspaceDeadlineActionView: '查看',
    workspaceDeadlineActionStart: '开始',
    workspaceDeadlineActionSnooze15: '延后15分',
    workspaceDeadlineActionSnooze30: '延后30分',
    details: '详情',
    openDetails: '打开详情',
    minimizeWindow: '窗口最小化',
    maximizeWindow: '窗口最大化',
    restoreWindow: '窗口还原',
    themeTransitionCircle: '圆形扩散',
    themeTransitionHeart: '柔和扩散',
    workspaceHint: '笔记、任务与专注的一体工作台',
    switchToWorkspace: '打开工作台',
    switchToCompact: '简洁模式',
    collapseSidebar: '收起侧栏',
    expandSidebar: '展开侧栏',
    themeLight: '浅色模式',
    themeDark: '深色模式',
    settingsTitle: '设置',
    starOnGithub: '在 GitHub 上点星',
    general: '常规',
    autoStart: '开机自启',
    showPanelOnStartup: '启动时显示主窗口',
    markdownStorageTitle: '存储与互操作',
    markdownStorageModeLabel: 'Markdown 存储模式',
    markdownStorageModeHint: '可使用应用默认目录，也可以直接指向外部工作区，例如 Obsidian Vault。',
    markdownStorageModeAppDefault: '应用默认目录',
    markdownStorageModeCustomDirectory: '自定义目录',
    markdownStorageRootLabel: '自定义 Markdown 目录',
    markdownStorageRootHint: '填入一个目录路径；如目录不存在，后续会自动补齐 notes / review / attachments。',
    markdownStorageRootPlaceholder: '/path/to/your/markdown/workspace',
    markdownStorageResolvedRootLabel: '当前实际存储根目录',
    markdownStorageResolvedRootHint: '这里显示后续 Markdown 文件真正使用的根目录。',
    markdownStorageStatusReady: '已就绪',
    markdownStorageStatusMissing: '待创建',
    markdownStorageApply: '应用存储路径',
    markdownStorageApplying: '应用中...',
    markdownStorageApplySuccess: 'Markdown 存储路径已更新。',
    markdownStorageExport: '导出 Markdown',
    markdownStorageExporting: '导出中...',
    markdownStorageExportSuccess:
      '已将 {count} 个 Markdown 文件导出到当前存储工作区，并复制 {attachments} 个附件。',
    markdownStorageImport: '导入 Markdown',
    markdownStorageImporting: '导入中...',
    markdownStorageImportSuccess:
      '已导入 {imported} 个 Markdown 文件，更新 {updated} 个已有文件，并恢复 {attachments} 个附件。',
    markdownStorageImportPreviewFailed: 'Markdown 导入预检失败。',
    markdownStorageImportPreviewEmpty: '当前 notes/ 或 review/ 下没有可导入的 Markdown 文件。',
    markdownStorageImportCancelled: '已取消 Markdown 导入。',
    markdownStorageImportPreviewConfirm:
      'Markdown 导入预检：\\n- 扫描文件：{scanned}\\n- 新增导入：{import}\\n- 覆盖更新：{update}\\n- 恢复附件：{attachments}\\n- 缺少 note_id：{withoutId}\\n\\n确认继续导入吗？',
    proMode: '隐藏提示',
    showStickyToggleOnHome: '贴纸显示控制常驻简洁模式主页',
    shortcuts: '快捷键',
    shortcutToggle: '切换主窗口: Ctrl+Shift+N',
    shortcutOverlay: '切换贴纸全局操作: Ctrl+Shift+O',
    shortcutStickyHide: '隐藏/显示顶层贴纸: Ctrl+Shift+H',
    shortcutToggleLabel: '切换主窗口',
    shortcutOverlayLabel: '切换贴纸全局操作',
    shortcutStickyHideLabel: '隐藏/显示贴纸',
    shortcutFormatHint: '使用类似 Ctrl+Shift+N 的格式；留空表示禁用该快捷键。',
    shortcutApply: '应用',
    shortcutSaving: '保存中...',
    shortcutStatusRegistered: '已注册',
    shortcutStatusPending: '待应用',
    shortcutStatusConflict: '冲突：已被其他应用或其他动作占用',
    shortcutStatusInvalid: '快捷键格式无效',
    shortcutStatusDisabled: '已禁用',
    shortcutStatusError: '注册失败',
    shortcutStatusRegisteredHint: '该快捷键已经注册成功，当前会立即响应全局快捷键。',
    shortcutStatusPendingHint: '你修改了输入值，但还没有点应用；当前真正生效的仍然是上一次已应用的快捷键。',
    shortcutStatusConflictHint: '该快捷键注册失败，通常是被其他应用或另一个动作占用了。',
    shortcutStatusInvalidHint: '快捷键格式不合法，请使用类似 Ctrl+Shift+N 的格式。',
    shortcutStatusDisabledHint: '当前动作没有注册全局快捷键；留空就是显式禁用。',
    shortcutStatusErrorHint: '注册时出现了其他运行时错误；悬浮提示会附带底层错误信息。',
    shortcutEsc: '隐藏/退出交互: Escape (Esc)',
    shortcutPinSave: '保存并置顶: Ctrl+Enter',
    version: '版本 v1.0.0',
    close: '关闭',
    notesStorageRecoveryTitle: '笔记数据需要恢复',
    notesStorageRecoveryBody: '无法读取笔记数据文件。为保护现有数据，已禁用写入操作。',
    openNotesDataDirectory: '打开数据目录',
    feedbackCommunityEyebrow: '反馈交流',
    feedbackCommunityTitle: '交流反馈群',
    feedbackCommunityHint: '扫码加入交流群，提交问题、反馈想法，或者和我们交流使用体验。',
    feedbackCommunityCaption: '遇到问题或有建议，欢迎扫码进群反馈。',
    feedbackCommunityDevCaption: '打包后的正式应用里也可以直接看到这个二维码。',
    noteEditorPlaceholder: '在这里写下内容，支持 Markdown。',
    noteOpacityHud: '透明度',
    noteFrostHud: '磨砂',
    stickyAutoHideEnable: '启用溢边隐藏',
    stickyAutoHideDisable: '关闭溢边隐藏',
    workspaceQuickNoteHint: '输入后回车快速创建，或点 + 新建笔记。',
    workspaceCreateNote: '新建笔记',
    pomodoro: '番茄钟',
    pomodoroFocus: '专注',
    pomodoroShortBreak: '短休息',
    pomodoroLongBreak: '长休息',
    pomodoroRound: '轮次',
    pomodoroTask: '任务',
    pomodoroTaskElapsed: '已累计',
    pomodoroTaskCompleted: '已达标',
    pomodoroTasksCompleted: '达标任务',
    pomodoroTaskRounds: '任务次数',
    pomodoroTaskCurrentRound: '当前轮',
    pomodoroTaskModeDuration: '时长型',
    pomodoroTaskModeTimeWindow: '时间窗',
    pomodoroTaskTargetMinutes: '目标分钟数',
    pomodoroTaskFlexibleSchedule: '自由时长',
    pomodoroTaskPlanner: '专注任务规划',
    pomodoroTaskTitle: '任务标题',
    pomodoroNoTaskSelected: '未选择',
    pomodoroNoTasksToday: '今天暂无专注任务',
    pomodoroTaskRollup: '任务总计',
    pomodoroCompletedSessions: '完成整番茄',
    pomodoroTaskSettingsTitle: '番茄任务设置',
    pomodoroTaskSettingsHint: '这里仅保留任务开始提醒设置。',
    pomodoroStats: '统计',
    pomodoroTodayFocusMinutes: '今日专注',
    pomodoroTodayPomodoros: '今日番茄总数',
    pomodoroTodayPomodorosHint: '统计今天完成的番茄总数（所有任务）。单任务番茄数在任务列表中查看。',
    pomodoroFocusMinutesHint: '完成一个完整番茄周期后才会计数。修改用于后续新的周期。',
    pomodoroWeekFocusMinutes: '最近7天专注',
    pomodoroWeekPomodoros: '最近7天番茄数',
    pomodoroWeekAverageMinutes: '7天日均专注',
    pomodoroStreakDays: '连续专注',
    pomodoroBestDay: '最佳单日',
    pomodoroHeatmap28Days: '最近28天热力图',
    pomodoroTaskDistributionToday: '今日任务分布',
    pomodoroStart: '开始',
    pomodoroResume: '继续',
    pomodoroPause: '暂停',
    pomodoroSkip: '跳过',
    pomodoroFocusMinutes: '单个番茄时长（分钟）',
    pomodoroShortBreakMinutes: '短休息（分钟）',
    pomodoroLongBreakMinutes: '长休息（分钟）',
    pomodoroLongBreakEvery: '长休息每',
    pomodoroMiniBreakEveryMinutes: '小休每隔（分钟）',
    pomodoroMiniBreakDurationSeconds: '小休时长（秒）',
    pomodoroLongBreakEveryMinutes: '长休每隔（分钟）',
    pomodoroLongBreakDurationMinutes: '长休时长（分钟）',
    pomodoroBreakNotifyBeforeSeconds: '提前提醒（秒）',
    pomodoroMiniBreakIn: '下次小休',
    pomodoroLongBreakIn: '下次长休',
    pomodoroBreakNotifyStatus: '提醒状态',
    pomodoroBreakNotifyOn: '已开启',
    pomodoroBreakNotifyOff: '未开启',
    pomodoroBreakActionPanel: '休息控制',
    pomodoroBreakRunning: '休息倒计时进行中',
    pomodoroBreakPostponeTwoMinutes: '延后 2 分钟',
    pomodoroBreakRemaining: '剩余',
    pomodoroBreakStartNow: '开始休息',
    pomodoroBreakWaitState: '等待休息触发',
    pomodoroBreakActionHint: '开启提醒后，会按你设置的短休/长休间隔自动触发休息提醒。',
    pomodoroBreakSessionActive: '全局暂停休息',
    pomodoroBreakSessionNone: '未启用全局暂停',
    pomodoroBreakSession30m: '30分钟',
    pomodoroBreakSession1h: '1小时',
    pomodoroBreakSession2h: '2小时',
    pomodoroBreakSessionToday: '今天内',
    pomodoroBreakSessionClear: '取消暂停',
    pomodoroBreakControlEnable: '开启提醒',
    pomodoroBreakControlDisable: '关闭提醒',
    pomodoroBreakToggleLabel: '休息开关',
    pomodoroToggleOff: '关闭',
    pomodoroToggleOn: '开启',
    pomodoroBreakPausePreset: '暂停预设',
    pomodoroBreakReminderMode: '提醒方式',
    pomodoroBreakReminderModeFullscreen: '全屏提醒',
    pomodoroBreakReminderModePanel: '轻提示',
    pomodoroBreakReminderModeFullscreenHint: '在当前工作台窗口显示全屏休息提醒。',
    pomodoroBreakReminderModePanelHint: '仅显示轻量提示卡片，不接管整窗。',
    pomodoroBreakReminderEnabled: '休息提醒已开启',
    pomodoroBreakReminderDisabled: '休息提醒已关闭',
    pomodoroBreakSessionScopeGlobal: '独立运行',
    pomodoroBreakSessionScopeTask: '绑定任务',
    pomodoroBreakSessionBindTaskHint: '请先选择任务，再开启绑定任务模式。',
    pomodoroBreakSessionIndependentHint: '独立运行，不绑定任务',
    pomodoroBreakScheduleSourceIndependent: '独立间隔',
    pomodoroBreakScheduleTaskResolved: '当前任务节奏',
    pomodoroBreakScheduleIndependentMini: '独立小休间隔（分钟）',
    pomodoroBreakScheduleIndependentLong: '独立长休间隔（分钟）',
    pomodoroBreakQuickTest: '快速测试',
    pomodoroBreakQuickMini10s: '短休 10秒',
    pomodoroBreakQuickLong10s: '长休 10秒',
    pomodoroMiniBreakSoon: '小休即将开始',
    pomodoroLongBreakSoon: '长休即将开始',
    pomodoroMiniBreakNow: '该小休息了',
    pomodoroLongBreakNow: '该长休息了',
    pomodoroBreakIn: '休息倒计时',
    pomodoroBreakDuration: '休息时长',
    pomodoroTaskStartSoon: '任务即将开始',
    pomodoroTaskStartAt: '开始时间',
    pomodoroTaskStartLead: '提前',
    pomodoroBreakNotifyHint: '如需休息提醒，请允许系统通知权限。',
    pomodoroTaskStartReminderToggle: '任务开始提醒',
    pomodoroTaskStartReminderLeadMinutes: '提前提醒（分钟）',
    pomodoroTaskReminderDefaultLeadMinutes: '默认提前提醒（分钟）',
    workspaceRecoverPinnedStickiesTitle: '找回贴纸',
    workspaceRecoverPinnedStickiesHint: '如果贴纸被拖到屏幕外，一键把所有已钉住贴纸带回主屏可视区。',
    workspaceRecoverPinnedStickiesAction: '立即找回',
    workspaceRecoverPinnedStickiesRunning: '正在找回...',
    pomodoroTaskReminderQuickTest: '快速测试',
    pomodoroTaskReminderQuickNow: '立即触发',
    pomodoroMiniBreakPostponeMinutes: '小休延后（分钟）',
    pomodoroLongBreakPostponeMinutes: '长休延后（分钟）',
    pomodoroBreakPostponeLimit: '可延后次数',
    pomodoroBreakStrictMode: '严格休息模式',
    workspacePlannerShowingAllHint: '今日无匹配任务，已展示全部任务',
    workspacePlannerTodayMatched: '今日匹配',
    workspaceFocusEditSettings: '编辑设置',
    workspaceFocusHideSettings: '收起设置',
    workspaceMultiScreenHint: '提示会跟随当前工作台窗口，适配多屏场景。',
    recurrenceNone: '单次',
    recurrenceDaily: '每天',
    recurrenceWorkday: '工作日',
    recurrenceCustom: '自定义',
    addTask: '添加任务',
    weekdayMon: '周一',
    weekdayTue: '周二',
    weekdayWed: '周三',
    weekdayThu: '周四',
    weekdayFri: '周五',
    weekdaySat: '周六',
    weekdaySun: '周日'
  }
};

/** @param {string} locale */
export function getStrings(locale) {
  return strings[locale === 'zh' ? 'zh' : 'en'] || strings.en;
}
